package day42_Exceptions;

public class ThrowsKeyword2 {

    public static void main(String[] args) throws ArithmeticException {

        System.out.println("Test started");

        System.out.println(8/0);

        System.out.println("Test completed");

    }

    /*
    UNCHECKED EXCEPTIONS:
    Try Catch is the only way to handle unchecked exceptions.
    */

}
